### ISSUE TITLE
Switch to httr

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/sotkanet#2]
rOpenSci instructions: For http requests we strongly recommend using httr over RCurl

**Comment by vsaaristo** [comment]
Apparently RCurl was built to use TLS v1.0. Getting rid of this dependency would make the package applicable also when a higher level of security (i.e. TLS v1.2) is required.

**Comment by pitkant** [comment]
The current solution provided by @vsaaristo replaced RCurl-function with base-R functions to manipulate connections (url() ). This is smart enough to use WinINet functions under Windows and libcurl-functions under Linux and MacOS. It seems to be working well at the moment but I'm wondering if using httr would have its benefits under some circumstances. 

However, httr seems to have its own problems when operating behind a firewall, see this issue in Eurostat-package for example: https://github.com/rOpenGov/eurostat/issues/185

Since the package currently does not RCurl nor httr, should we be satisfied with using base R functions only and close this issue?

**Comment by antagomir** [comment]
Ok to me unless there are other arguments.

**Comment by vsaaristo** [comment]
I was wondering if a httr-based solution would perform any faster?

**Comment by pitkant** [comment]
My understanding is that httr is essential if the API needs any kind of authentication, tokens or similar. Which we don't need as sotkanet does not currently require them. It's actually a plus in my books if we can avoid dependencies, but this should be re-evaluated if they start requiring those.

I don't know about speed but I don't think it's an issue here, end user's internet connection is probably more important in that regard.

**Comment by antagomir** [comment]
I agree that avoiding dependencies is good unless clear improvements could be shown.

**Comment by pitkant** [comment]
The package uses httr since commit 6a18fca8f505a92fe8f2e38cb296bde358eb021e

**Comment by pitkant** [comment]
Using httr in newest CRAN release 0.9.79. If there are problems in any OS open a new issue
